databaseConfiguration:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3307/BookStore?autoReconnect=true
  properties:
    charSet: UTF-8
    # Connection Related Properties
    hibernate.connection.provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider

    # Hikari Connection Pool Configurations
    hibernate.hikari.maximumPoolSize: 20
    hibernate.hikari.idleTimeout: 60000
    hibernate.hikari.poolName: fquick_asl_orchestrator_pool
    hibernate.hikari.connectionTimeout: 6000
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

swaggerConfig:
  swaggerHost: localhost
  swaggerPort: 21900


server:
  applicationConnectors:
  - type: http
    port: 17900
    acceptorThreads: 1
    outputBufferSize: 32KB
    inputBufferSize: 8KB
    maxRequestHeaderSize: 8KB
    maxResponseHeaderSize: 8KB
    reuseAddress: true
    soLingerTime: null
    useServerHeader: false
    useDateHeader: true
    useForwardedHeaders: true
    bindHost: null

  adminConnectors:
  - type: http
    port: 17901

  minThreads: 8
  maxThreads: 1024
  idleThreadTimeout: 200s
  shutdownGracePeriod: 5s

  requestLog:
      timeZone: IST
      appenders:
      - type: file
        currentLogFilename: /var/log/flipkart/sp/sp-seller-support-sample-bookstore-master-access.log
        archivedLogFilenamePattern: /var/log/flipkart/sp-seller-support/sp-seller-support-sample-bookstore-master-access-%d.log
        logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %c{1.}: %m\n%ex"

logging:
  level: INFO
  appenders:
  - type: file
    currentLogFilename: /var/log/flipkart/sp/sp-seller-support-sample-bookstore-master-access.log
    archivedLogFilenamePattern: /var/log/flipkart/sp-seller-support/sp-seller-support-sample-bookstore-master-access-%d.log
  - type: console
    threshold: ALL
    timeZone: IST
    logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %c{1.}: %m\n%ex"

